#!/usr/bin/env python3
"""
sync_obsidian_index.py — Build a flat scannable index of the Obsidian vault.

Scans all .md files in ~/Obsidian/ (excluding .obsidian/), extracts:
- filename and path
- YAML frontmatter (type, domain, connected_to, source)
- First heading (# Title)
- Key Numbers section if present

Writes ~/Obsidian/_index.md — a single file agents can read to discover
what knowledge exists without ripgreping the entire vault.

Called by beacon_sync.py on every cron run, and by beacon_watcher.py
whenever Obsidian content changes.

Usage:
  python -m agent_env.sync_obsidian_index [--config PATH]
"""

import re
import sys
from datetime import datetime

from agent_env.environment import Environment, parse_config_arg

# Directories to skip
SKIP_DIRS = {".obsidian", ".git", "_templates"}


def parse_frontmatter(text):
    """Extract YAML frontmatter as a dict."""
    if not text.startswith("---"):
        return {}
    end = text.find("---", 3)
    if end == -1:
        return {}
    fm_text = text[3:end].strip()
    result = {}
    for line in fm_text.split("\n"):
        if ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            result[key] = val
    return result


def extract_headings(text):
    """Extract first H1 heading."""
    for line in text.split("\n"):
        if line.startswith("# ") and not line.startswith("## "):
            return line[2:].strip()
    return ""


def extract_key_numbers(text):
    """Extract Key Numbers section if present."""
    in_section = False
    lines = []
    for line in text.split("\n"):
        if line.strip().lower().startswith("key numbers"):
            in_section = True
            continue
        if in_section:
            if line.startswith("## ") or line.startswith("# "):
                break
            if line.strip():
                lines.append(line.strip())
    return " | ".join(lines) if lines else ""


def scan_vault(env):
    """Scan Obsidian vault and build index entries."""
    obsidian = env.obsidian
    if not obsidian.exists():
        return []

    entries = []
    for md_file in sorted(obsidian.rglob("*.md")):
        # Skip .obsidian config, templates, and the auto-generated index itself
        parts = md_file.relative_to(obsidian).parts
        if any(p in SKIP_DIRS for p in parts):
            continue
        if md_file.name == "_index.md":
            continue

        try:
            text = md_file.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue

        fm = parse_frontmatter(text)
        heading = extract_headings(text)
        key_nums = extract_key_numbers(text)
        rel_path = md_file.relative_to(obsidian)

        entries.append({
            "path": f"~/Obsidian/{rel_path}",
            "title": fm.get("title", "") or heading or md_file.stem,
            "type": fm.get("type", ""),
            "domain": fm.get("domain", ""),
            "connected_to": fm.get("connected_to", ""),
            "source": fm.get("source", ""),
            "key_numbers": key_nums,
            "has_links": "[[" in text,
        })

    return entries


def build_index(entries):
    """Build the _index.md content."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Obsidian Vault Index",
        "",
        f"> Auto-generated by sync_obsidian_index.py — {now}",
        f"> {len(entries)} notes indexed. Read this first to discover what knowledge exists.",
        "",
        "## How to Use",
        "",
        "1. Scan the table below for relevant notes",
        "2. Read the full note: `cat '<path>'`",
        "3. Follow `[[links]]` to related concepts",
        "4. For queries across notes, use gbrain search (if installed)",
        "",
        "## Notes",
        "",
        "| Title | Type | Domain | Key Numbers | Links |",
        "|-------|------|--------|-------------|-------|",
    ]

    for e in entries:
        title = e["title"][:50]
        type_tag = e["type"] or "—"
        domain = e["domain"] or "—"
        key_nums = e["key_numbers"][:60] if e["key_numbers"] else "—"
        links = "✓" if e["has_links"] else "—"
        lines.append(f"| {title} | {type_tag} | {domain} | {key_nums} | {links} |")

    # Add connected concepts section (edges extracted from frontmatter)
    edges = []
    for e in entries:
        if e["connected_to"]:
            # Parse [[link]] or comma-separated concepts
            concepts = re.findall(r'\[\[(.*?)\]\]', e["connected_to"])
            if not concepts:
                concepts = [c.strip() for c in e["connected_to"].split(",")]
            for c in concepts:
                edges.append((e["title"], c))

    if edges:
        lines += [
            "",
            "## Concept Graph",
            "",
            "| From | Connects To |",
            "|------|-------------|",
        ]
        for src, tgt in edges:
            lines.append(f"| {src[:50]} | {tgt[:50]} |")

    lines += [
        "",
        "---",
        f"*Last synced: {now}*",
    ]

    return "\n".join(lines)


def sync(env):
    """Rebuild ~/Obsidian/_index.md from the vault. Returns 1 if it changed, else 0.

    This is the import entry point used by beacon_sync (no subprocess)."""
    index_path = env.obsidian / "_index.md"
    entries = scan_vault(env)
    content = build_index(entries)

    existing = ""
    if index_path.exists():
        existing = index_path.read_text(encoding="utf-8", errors="replace")

    if content.strip() != existing.strip():
        index_path.parent.mkdir(parents=True, exist_ok=True)
        index_path.write_text(content, encoding="utf-8")
        print(f"  Updated Obsidian index: {len(entries)} notes")
        return 1
    print(f"  Obsidian index unchanged: {len(entries)} notes")
    return 0


def main():
    config_path, _ = parse_config_arg(sys.argv[1:])
    env = Environment.load(config_path)
    sync(env)


if __name__ == "__main__":
    main()
